name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2 # Change this to your region
  LIGHTSAIL_SERVICE_NAME: revival-service # Change to your service name
  DOCKER_IMAGE_NAME: afalcon26/revival-backend # Change to your image name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Lightsail
        run: |
          aws lightsail create-container-service-deployment \
            --service-name ${{ env.LIGHTSAIL_SERVICE_NAME }} \
            --containers '{
              "flask-app": {
                "image": "${{ env.DOCKER_IMAGE_NAME }}:latest",
                "ports": {
                  "5000": "HTTP"
                }
              }
            }' \
            --public-endpoint '{
              "containerName": "flask-app",
              "containerPort": 5000,
              "healthCheck": {
                "healthyThreshold": 2,
                "unhealthyThreshold": 2,
                "timeoutSeconds": 2,
                "intervalSeconds": 5,
                "path": "/",
                "successCodes": "200-499"
              }
            }'
